---
title: "R Notebook"
output: html_notebook
---

```{r setup}
library(tidyverse)
```

```{r}
df <- data.frame(
  stringsAsFactors = FALSE,
       check.names = FALSE,
          Assembly = c("v4.1 (Chalhoub et al., 2014)",
                       "v4.1 (Chalhoub et al., 2014)",
                       "v4.1 (Chalhoub et al., 2014)","v4.1 (Chalhoub et al., 2014)",
                       "v4.1 (Chalhoub et al., 2014)","v4.1 (Chalhoub et al., 2014)",
                       "v4.1 (Chalhoub et al., 2014)","v4.1 (Chalhoub et al., 2014)",
                       "v4.1 (Chalhoub et al., 2014)",
                       "v4.1 (Chalhoub et al., 2014)","v4.1 (Chalhoub et al., 2014)",
                       "v4.1 (Chalhoub et al., 2014)","v4.1 (Chalhoub et al., 2014)",
                       "v4.1 (Chalhoub et al., 2014)","v4.1 (Chalhoub et al., 2014)",
                       "v4.1 (Chalhoub et al., 2014)","v4.1 (Chalhoub et al., 2014)",
                       "v4.1 (Chalhoub et al., 2014)",
                       "v4.1 (Chalhoub et al., 2014)","NRGene","NRGene","NRGene","NRGene","NRGene",
                       "NRGene","NRGene","NRGene","NRGene","NRGene",
                       "NRGene","NRGene","NRGene","NRGene","NRGene","NRGene",
                       "NRGene","NRGene","NRGene"),
    Pseudomolecule = c("chrA01","chrA02","chrA03",
                       "chrA04","chrA05","chrA06","chrA07","chrA08","chrA09",
                       "chrA10","chrC01","chrC02","chrC03","chrC04",
                       "chrC05","chrC06","chrC07","chrC08","chrC09","chrA01",
                       "chrA02","chrA03","chrA04","chrA05","chrA06","chrA07",
                       "chrA08","chrA09","chrA10","chrC01","chrC02",
                       "chrC03","chrC04","chrC05","chrC06","chrC07","chrC08",
                       "chrC09"),
         `DNA/DTA` = c(0.21,0.24,0.21,0.2,0.21,
                       0.23,0.21,0.17,0.32,0.14,0.99,0.46,0.66,0.57,0.52,
                       0.45,0.48,0.4,0.49,0.33,0.33,0.29,0.25,0.32,
                       0.31,0.3,0.24,0.53,0.2,0.6,0.74,0.86,0.78,0.61,0.6,
                       0.68,0.57,0.68),
         `DNA/DTC` = c(0.43,0.51,0.44,0.37,0.39,
                       0.38,0.36,0.33,0.64,0.27,1.49,1.85,2.17,1.93,1.65,
                       1.4,1.6,1.37,2,0.71,0.93,0.61,0.51,0.68,0.56,
                       0.55,0.59,1.24,0.45,3.37,3.88,4.38,4.37,3.23,
                       2.67,3.26,2.81,4.1),
         `DNA/DTH` = c(0.24,0.28,0.28,0.18,0.21,
                       0.27,0.21,0.18,0.38,0.17,0.54,0.61,0.79,0.62,0.59,
                       0.51,0.56,0.49,0.63,0.32,0.38,0.33,0.22,0.27,
                       0.28,0.25,0.21,0.45,0.23,0.76,0.81,1.01,0.84,0.75,
                       0.66,0.71,0.71,0.87),
         `DNA/DTM` = c(0.48,0.54,0.49,0.38,0.48,
                       0.5,0.46,0.37,0.73,0.38,0.97,1.16,1.43,1.31,1.1,
                       0.92,1.07,0.98,1.19,2.49,2.08,1.27,1.39,0.82,
                       1.66,3.83,2.13,1.78,5.15,5.18,19.03,5.67,7.71,3.13,
                       3.82,8.87,4.25,4.87),
         `DNA/DTT` = c(0.1,0.14,0.14,0.09,0.09,
                       0.1,0.15,0.1,0.2,0.07,0.19,0.28,0.35,0.24,0.22,
                       0.2,0.25,0.22,0.26,0.12,0.15,0.15,0.1,0.1,0.11,
                       0.1,0.12,0.2,0.08,0.14,0.22,0.28,0.18,0.17,0.15,
                       0.2,0.17,0.18),
    `DNA/Helitron` = c(5.51,6.77,6.4,5.19,5.47,
                       5.96,5.88,4.7,8.89,3.8,8.58,11.01,13.96,12.01,9.51,
                       9.24,10.47,8.69,11.25,12.74,9.87,7.83,7.88,
                       10.24,9.12,7.64,6.7,15.77,5.84,14.69,17.96,20.14,
                       19.32,15.78,13.19,15.15,13.39,16.94),
       `LTR/Copia` = c(0.73,0.91,0.69,0.61,0.68,
                       0.71,0.74,0.72,1.06,0.42,2.51,2.96,3.36,3.42,2.62,
                       2.59,2.8,2.25,3.19,1.24,1.57,0.95,1.2,1.04,
                       0.99,3.12,1.18,1.95,1.05,5,18.91,6.61,9.18,5.24,
                       4.96,6.09,4.86,5.92),
       `LTR/Gypsy` = c(0.65,1.07,0.48,0.74,0.71,
                       1.27,0.82,0.73,0.84,0.99,4.02,5.19,5.3,4.36,4.92,
                       3.27,4.48,4.22,5.36,1.87,2.73,0.92,1.18,1.69,
                       2.23,2.79,1.79,3.64,2.23,6.56,13.9,9.01,8.39,8,
                       5.84,8.72,7.02,8.65),
     `LTR/unknown` = c(0.36,0.51,0.34,0.36,0.39,
                       0.46,0.4,0.38,0.55,0.35,1.49,1.98,1.95,1.66,1.58,
                       1.37,1.59,1.51,1.86,1.24,1.58,0.9,0.89,1.13,
                       1.83,1.74,1.16,2.28,1.17,3.66,14.56,5.28,5.26,4.22,
                       3.7,4.88,3.94,4.99),
    Low_complexity = c(0.05,0.05,0.07,0.04,0.04,
                       0.05,0.06,0.04,0.07,0.04,0.06,0.07,0.1,0.07,0.06,
                       0.06,0.06,0.06,0.07,0.06,0.07,0.08,0.05,0.06,
                       0.06,0.07,0.05,0.1,0.04,0.08,0.09,0.12,0.1,0.08,
                       0.07,0.09,0.08,0.09),
        `MITE/DTA` = c(0.09,0.11,0.12,0.08,0.08,
                       0.09,0.1,0.08,0.15,0.05,0.11,0.15,0.2,0.16,0.12,
                       0.13,0.13,0.12,0.15,0.11,0.13,0.12,0.09,0.09,
                       0.09,0.09,0.08,0.17,0.06,0.15,0.2,0.26,0.22,0.15,
                       0.16,0.18,0.16,0.18),
        `MITE/DTC` = c(0,0,0,0,0,0,0,0,0.01,0,
                       0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0,
                       0,0,0,0.01,0,0,0,0.01,0,0,0.01,0.01,0.01,
                       0.01,0,0,0.01,0.01),
        `MITE/DTH` = c(0.04,0.06,0.08,0.04,0.05,
                       0.05,0.06,0.04,0.08,0.03,0.08,0.11,0.14,0.11,0.09,
                       0.09,0.11,0.09,0.1,0.11,0.12,0.13,0.07,0.09,
                       0.11,0.11,0.08,0.17,0.07,0.14,0.17,0.22,0.19,0.15,
                       0.13,0.17,0.15,0.17),
        `MITE/DTM` = c(0.02,0.02,0.05,0.01,0.02,
                       0.02,0.02,0.01,0.03,0.02,0.18,0.18,0.15,0.2,0.08,
                       0.12,0.17,0.05,0.21,0.04,0.04,0.03,0.02,0.04,
                       0.03,0.03,0.02,0.06,0.02,0.14,0.17,0.18,0.19,0.12,
                       0.12,0.14,0.13,0.17),
        `MITE/DTT` = c(0,0,0,0,0,0,0,0,0.01,0,
                       0,0,0.01,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                       0,0,0.01,0.01,0.01,0,0.01,0.01,0.01,0),
     Simple_repeat = c(0.2,0.22,0.27,0.17,0.18,
                       0.23,0.23,0.16,0.39,0.16,0.26,0.31,0.43,0.3,0.28,
                       0.27,0.3,0.25,0.43,0.25,0.26,0.3,0.19,0.22,0.23,
                       0.25,0.2,0.38,0.19,0.34,0.45,0.55,0.44,0.36,
                       0.34,0.39,0.35,0.41)
)
```

```{r}
df %>% pivot_longer(cols=-c('Assembly', 'Pseudomolecule'), names_to='Repeat', values_to='Mbp') %>% 
  group_by(Assembly, Repeat) %>% 
  summarise(sums = sum(Mbp)) -> long_df
tail(long_df)
```
```{r}
long_df %>% 
  mutate(Assembly = factor(Assembly, levels = c( 'NRGene','v4.1 (Chalhoub et al., 2014)'))) %>%
  mutate(Repeat = str_replace_all(Repeat, '_',' ')) %>% 
  ggplot(aes(x = reorder(Repeat, -sums), fill = Assembly, y = sums)) +
  geom_bar(stat='identity', position = "dodge") +
  cowplot::theme_minimal_vgrid() +
  ylab('Size (Mbp)') +
  coord_flip() + 
  xlab('Repeat-class') -> p
p
```
```{r}
cowplot::save_plot('FigS2.png',p, base_height = 5)
```

